[theme]
primaryColor = "#1f77b4"  # Основной цвет (кнопки, акценты)
backgroundColor = "#FFFFFF" # Цвет фона приложения
secondaryBackgroundColor = "#F0F2F6" # Цвет фона сайдбара и блоков
textColor = "#262730" # Цвет текста
font = "sans serif" # Шрифт (sans serif, serif, monospace)